version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: epildev-app-prod
    ports:
      - "100:80"    # Frontend (nginx) - Cloudflare will access on port 100
      - "200:200"   # Backend API - Cloudflare will access on port 200
    environment:
      - NODE_ENV=production
      - PORT=200
      - FRONTEND_URL=http://localhost:100
      - CORS_ORIGINS=https://8bp.epildevconnect.uk,http://8bp.epildevconnect.uk,https://epildevconnect.uk,http://epildevconnect.uk
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: epildev-network-prod
