version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: epildev-app
    ports:
      - "1001:80"    # Frontend (nginx)
      - "1002:1002"  # Backend API
    environment:
      - NODE_ENV=development
      - PORT=1002
      - FRONTEND_URL=http://localhost:1001
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: epildev-network
