version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${localhost_fe:-1001}:${localhost_fe:-1001}"
    environment:
      - VITE_API_URL=http://localhost:${localhost_be:-1002}
      - VITE_LOCALHOST_FE=${localhost_fe:-1001}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - epildev-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${localhost_be:-1002}:${localhost_be:-1002}"
    environment:
      - NODE_ENV=production
      - PORT=${localhost_be:-1002}
      - LOCALHOST_BE=${localhost_be:-1002}
      - LOCALHOST_FE=${localhost_fe:-1001}
      - FRONTEND_URL=http://localhost:${localhost_fe:-1001}
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./data:/app/data
    networks:
      - epildev-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - epildev-network

networks:
  epildev-network:
    driver: bridge

volumes:
  data:


