version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: epildev-app-prod
    ports:
      - "100:80"    # Frontend 1 (nginx) - Cloudflare will access on port 100
      - "300:80"    # Frontend 2 (nginx) - Cloudflare will access on port 300
      - "200:200"   # Backend API - Cloudflare will access on port 200
    environment:
      - NODE_ENV=production
      - PORT=200
      - FRONTEND_URL=https://${FRONTEND_DOMAIN_1}
      - FRONTEND_DOMAIN_1=${FRONTEND_DOMAIN_1}
      - FRONTEND_DOMAIN_2=${FRONTEND_DOMAIN_2}
      - CORS_ORIGINS=https://${FRONTEND_DOMAIN_1},http://${FRONTEND_DOMAIN_1},https://${FRONTEND_DOMAIN_2},http://${FRONTEND_DOMAIN_2},https://epildevconnect.uk,http://epildevconnect.uk,https://${API_ENDPOINTS},http://${API_ENDPOINTS}
    env_file:
      - .env
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  default:
    name: epildev-network-prod
